name = "java-rs"
title = "Java RS Driver"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

# toc_landing_pages = ["/paths/to/pages/that/have/nested/content"]

[constants]
driver-short = "Java RS driver"
driver-long = "MongoDB Java Reactive Streams Driver"
version = "5.0"
full-version = "{+version+}.0"
api = "https://mongodb.github.io/mongo-java-driver/{+version+}/apidocs"
rs-docs = "https://www.reactive-streams.org/reactive-streams-1.0.4-javadoc/org/reactivestreams"
driver-source-gh = "https://github.com/mongodb/mongo-java-driver"